# Generated by Django 3.2.4 on 2021-06-22 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210622_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetailsModel',
            fields=[
                ('emp_name', models.CharField(max_length=100)),
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('working_hours', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLoginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_in', models.TimeField()),
                ('punch_out', models.TimeField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employeemodel')),
            ],
        ),
        migrations.RemoveField(
            model_name='employeepunchoutmodel',
            name='emp_id',
        ),
        migrations.DeleteModel(
            name='EmployeePunchInModel',
        ),
        migrations.DeleteModel(
            name='EmployeePunchOutModel',
        ),
    ]
